# --- Main Colors ---
background            #1a1112
foreground            #f0dedf
cursor                #f0dedf
cursor_text_color     #1a1112

selection_background  #5c3f43
selection_foreground  #ffd9dd

url_color             #eabf8f

# --- ANSI Colors ---
color0                #1a1112
color1                #ffb4ab
color2                #eabf8f
color3                #e5bdc1
color4                #ffb2bc
color5                #eabf8f
color6                #e5bdc1
color7                #f0dedf

color8                #524345
color9                #93000a
color10               #5e411c
color11               #5c3f43
color12               #72333e
color13               #5c3f43
color14               #5e411c
color15               #d7c1c3

# --- Starship Prompt Bubbles ---
color255              #72333e
color254              #ffb2bc
color253              #5c3f43
color252              #e5bdc1
color251              #5e411c
color250              #eabf8f
color249              #93000a
color248              #ffb4ab

color232              #ffd9dd
color233              #561d28
color234              #ffd9dd
color235              #43292d
color236              #ffddb8
color237              #452b07
color238              #ffdad6
color239              #690005
color240              #ffd9dd

# Matched with unthemed light/dark
color243              #ffb2bc
color244              #ffb4ab
color245              #524345

# --- UI Elements ---
active_tab_foreground   #561d28
active_tab_background   #ffb2bc
inactive_tab_foreground #ffd9dd
inactive_tab_background #72333e

active_border_color     #ffb2bc
inactive_border_color   #9f8c8e

# --- Marks ---
mark1_foreground        #3b0714
mark1_background        #ffd9dd
mark2_foreground        #2c1518
mark2_background        #ffd9dd
mark3_foreground        #2b1700
mark3_background        #ffddb8
