font_family      JetBrainsMono Nerd Font
font_size 12.0

confirm_os_window_close 0

window_padding_width 6
inactive_text_alpha 0.6

allow_hyperlinks yes
shell_integration enabled

macos_option_as_alt no
macos_quit_when_last_window_closed no
linux_display_server auto
wayland_titlebar_color system

active_tab_font_style   bold
inactive_tab_font_style normal

scrollback_lines 5000
scrollbar hovered
scrollbar_width 0.5

mouse_hide_wait 3.0
focus_follows_mouse no

enable_audio_bell no
visual_bell_duration 0.2

# shortcuts :

kitty_mod ctrl+shift

map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+s paste_from_selection

map kitty_mod+up    scroll_line_up
map kitty_mod+k     scroll_line_up
map kitty_mod+down  scroll_line_down
map kitty_mod+j     scroll_line_down
map kitty_mod+page_up   scroll_page_up
map kitty_mod+page_down scroll_page_down
map kitty_mod+home  scroll_home
map kitty_mod+end   scroll_end

map kitty_mod+enter new_window
map kitty_mod+n     new_os_window
map kitty_mod+w     close_window
map kitty_mod+]     next_window
map kitty_mod+[     previous_window
map kitty_mod+1     first_window
map kitty_mod+2     second_window
map kitty_mod+3     third_window
map kitty_mod+4     fourth_window
map kitty_mod+5     fifth_window
map kitty_mod+6     sixth_window
map kitty_mod+7     seventh_window
map kitty_mod+8     eighth_window
map kitty_mod+9     ninth_window
map kitty_mod+0     tenth_window

map kitty_mod+right next_tab
map kitty_mod+left  previous_tab
map kitty_mod+t     new_tab
map kitty_mod+q     close_tab
map kitty_mod+alt+t set_tab_title

map kitty_mod+equal  change_font_size all +2.0
map kitty_mod+minus  change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0

map kitty_mod+e     open_url_with_hints
map kitty_mod+p>f   kitten hints --type path --program -
map kitty_mod+p>l   kitten hints --type line --program -
map kitty_mod+p>w   kitten hints --type word --program -

map kitty_mod+f11   toggle_fullscreen
map kitty_mod+f2    edit_config_file
map kitty_mod+f5    load_config_file

